#! /usr/bin/env escript
%%! -pa ../ebin ../deps/socketio/ebin ../deps/socketio/deps/misultin/ebin ../deps/socketio/deps/ossp_uuid/ebin ../deps/socketio/deps/jsx/ebin
-mode(compile).
-compile(export_all).

main(_) ->
    appmon:start(),
    application:start(sasl),
    application:start(gproc),
    application:start(misultin),
    application:start(socketio),
    {ok, Pid} = socketio_listener:start([
        {http_port, 7878}, 
        {default_http_handler, webbus_http_handler}
    ]),
    EventMgr = socketio_listener:event_manager(Pid),
    ok = gen_event:add_handler(EventMgr, webbus_event_handler, []),
    receive _ -> ok end.
